# Generated by Django 4.2.11 on 2024-08-28 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('funding_start_date', models.DateField(blank=True, null=True)),
                ('funding_end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50, null=True)),
                ('risk_description', models.TextField(blank=True, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed')], max_length=50, null=True)),
                ('business_plan', models.FileField(blank=True, null=True, upload_to='business_plans/')),
                ('video_presentation', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('repayment_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('repayment_period', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('kiis_document', models.FileField(blank=True, null=True, upload_to='kiis_documents/')),
                ('fees_description', models.TextField(blank=True, null=True)),
                ('use_of_proceeds', models.TextField(blank=True, null=True)),
                ('current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shareholders_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_of_goods_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_invested', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_set_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments_in_projects', to='projects.project')),
            ],
        ),
    ]
