# Generated by Django 4.2.11 on 2024-09-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_health_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_history_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('business_viability_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('macroeconomic_factors_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.CharField(max_length=50)),
                ('suggested_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inflation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gdp_growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unemployment_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bond_yield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
