# Generated by Django 4.2.11 on 2024-08-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_health_score', models.IntegerField()),
                ('credit_history_score', models.IntegerField()),
                ('business_viability_score', models.IntegerField()),
                ('macroeconomic_factors_score', models.IntegerField()),
                ('overall_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
                ('suggested_interest_rate', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('inflation_rate', models.FloatField()),
                ('gdp_growth_rate', models.FloatField()),
                ('unemployment_rate', models.FloatField()),
                ('bond_yield', models.FloatField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
