# Generated by Django 4.2.11 on 2024-09-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk_analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditRiskAssessment',
        ),
    ]
