# Generated by Django 4.2.11 on 2024-08-13 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc_aml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_kyc', models.BooleanField(default=True, help_text='Toggle to activate or deactivate KYC Application.', verbose_name='Enable KYC Verification')),
                ('allow_resubmission', models.BooleanField(default=False, help_text='Toggle to allow clients to re-submit KYC applications after a failure.', verbose_name='Allow Re-submission')),
                ('number_kyc_tries', models.PositiveIntegerField(default=1, help_text='Number of attempts a client is allowed for KYC application.', verbose_name='Allowed KYC Tries')),
                ('run_check_on_expiry', models.BooleanField(default=False, help_text='Toggle to require KYC verification on ID expiry.', verbose_name='Request Verification on Expiry')),
                ('days_to_send_notification', models.PositiveIntegerField(default=30, help_text='Number of days before ID expiration to send a notification.', verbose_name='Verification Notification (Days)')),
                ('review_frequency', models.PositiveIntegerField(default=30, help_text='Frequency in days for reviewing KYC applications.', verbose_name='Review Frequency (Days)')),
                ('kyc_system_type', models.CharField(blank=True, choices=[('manual', 'Manual KYC'), ('automatic', 'Automatic KYC')], max_length=9, null=True, verbose_name='KYC System')),
            ],
            options={
                'verbose_name': 'KYC Settings',
                'verbose_name_plural': 'KYC Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='kycapplication',
            options={'permissions': [('verify_kyc', 'Verify KYC Application'), ('reject_kyc', 'Reject KYC Application'), ('merge_kyc', 'Merge KYC data with user information')], 'verbose_name': 'KYC Application', 'verbose_name_plural': 'KYC Applications'},
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='second_citizenship',
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='accept_terms',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has accepted terms and conditions.', verbose_name='Accepted Terms'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='address_line_1',
            field=models.CharField(help_text="Primary address line of the user. Must be from the user's country of residence.", max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Secondary address line of the user.', max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='address_proof_type',
            field=models.CharField(choices=[('BANK_STATEMENT', 'Bank Statement'), ('CREDIT_CARD_STATEMENT', 'Credit Card Statement'), ('UTILITY', ' Utility Bill')], default='BANK_STATEMENT', help_text='Type of document provided as proof of address.', max_length=21, verbose_name='Proof of Address Type'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='agreed_to_data_usage',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has consented to data usage.', verbose_name='Agreed to Data Usage'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Date of birth as per the identification document. Must match the user's ID.", null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='city',
            field=models.CharField(help_text="City of the user's address.", max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='country_residence',
            field=models.ForeignKey(blank=True, help_text='Country where the user primarily resides.', on_delete=django.db.models.deletion.CASCADE, related_name='kyc_residence_country', to='locations.country', verbose_name='Country of Residence'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary e-mail address of the user.', max_length=150, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='identification_expiry',
            field=models.DateField(blank=True, help_text='Date of expiry of the identification document.', null=True, verbose_name='ID Expiry Date'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='identification_issue_date',
            field=models.DateField(blank=True, help_text='Date of issue of the identification document.', null=True, verbose_name='ID Issue Date'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='identification_number',
            field=models.CharField(blank=True, help_text='Identification document number (e.g., passport number).', max_length=50, null=True, verbose_name='Identification Number'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='identification_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport')], default='PASSPORT', help_text='Type of identification document provided by the user.', max_length=21, verbose_name='Photo ID Type'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='kyc_country',
            field=models.ForeignKey(blank=True, help_text='Country for which KYC is performed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kyc_kyc_country', to='locations.country', verbose_name='KYC Country'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='kyc_refused_code',
            field=models.CharField(blank=True, choices=[('EXPIRED_DOCUMENT', 'Document Expired'), ('DOCUMENT_DOES_NOT_MATCH_USER_DATA', 'Document does not match user data')], help_text='Code indicating the reason for KYC refusal.', max_length=34, null=True, verbose_name='KYC Refused Code'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='kyc_review_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Date when KYC was reviewed.', null=True, verbose_name='KYC Checked Date'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='kyc_status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the KYC application.', max_length=28, verbose_name='KYC Status'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='kyc_status_note',
            field=models.TextField(blank=True, editable=False, help_text='Notes or reasons for the current KYC status.', max_length=255, null=True, verbose_name='KYC Status Note'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='kyc_submitted_ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, help_text='IP address recorded at the time of KYC submission.', null=True, verbose_name='KYC Submitted IP'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='legal_first_names',
            field=models.CharField(blank=True, help_text='First names of the user as shown in documents.', max_length=255, null=True, verbose_name='Legal First Names'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='legal_last_names',
            field=models.CharField(blank=True, help_text='Last names of the user as shown in documents.', max_length=255, null=True, verbose_name='Legal Last Names'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='photo_id',
            field=models.FileField(help_text="Front side of the user's Photo Identification.", upload_to='uploads/kyc/', verbose_name='Photo ID (Front)'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='photo_id_back',
            field=models.FileField(blank=True, help_text="Back side of the user's Photo Identification.", null=True, upload_to='uploads/kyc/', verbose_name='Photo ID (Back)'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text='Place of birth of the user.', max_length=255, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='politically_exposed_person',
            field=models.CharField(choices=[('pep', 'Yes, I am politically exposed'), ('non_pep', "No, I'm not politically exposed")], default='not_pep', help_text='Indicates if the user is a Politically Exposed Person.', max_length=16, verbose_name='Politically Exposed Person (PEP)'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='proof_of_address_document',
            field=models.FileField(help_text='Document showing name and address, not older than 90 days.', upload_to='uploads/kyc/', verbose_name='Proof of Address'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='registered_ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, help_text='IP address recorded at the time of user registration.', null=True, verbose_name='Registered IP'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='User who reviewed the KYC application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='reviewer_ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, help_text='IP address of the reviewer.', null=True, verbose_name='Reviewer IP Address'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='selfie_with_id',
            field=models.FileField(blank=True, help_text='Selfie with the user holding their ID.', null=True, upload_to='uploads/kyc/', verbose_name='Selfie with ID'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='state',
            field=models.CharField(help_text="State/Region/Province of the user's address.", max_length=255, verbose_name='State/Region'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='status_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of the last status update.', verbose_name='Status Update Time'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='us_citizen_tax_resident',
            field=models.BooleanField(default=False, help_text='Indicates whether the user is a US citizen or tax resident.', verbose_name='US Citizen or Tax Resident'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='user',
            field=models.ForeignKey(help_text='User associated with this KYC application.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='KYC User'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='zip_code',
            field=models.CharField(help_text="Postal code of the user's address.", max_length=10, verbose_name='Zip Code'),
        ),
    ]
