# Generated by Django 4.2.11 on 2024-08-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_aml', '0002_kycsetting_alter_kycapplication_options_and_more'),
    ]

    operations = [
    ]
