# Generated by Django 4.2.11 on 2024-08-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20240815_1347'),
        ('kyc_aml', '0004_alter_kycapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='citizenship',
            field=models.ForeignKey(default=5, help_text='The citizenship of the user submitting KYC application. A proof of such citizenship is required by form of National ID or Passport.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.country', verbose_name='Citizenship'),
        ),
    ]
