# Generated by Django 4.2.11 on 2024-08-13 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Registered User', 'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('borrower', 'Borrower'), ('investor', 'Investor')], default='investor', help_text='The account type of the user.', max_length=8, null=True, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, help_text='The contact number of the user.', max_length=50, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='country_of_residence',
            field=models.ForeignKey(blank=True, help_text='The country of residence of the user. KYC verification will be applied to this country and the user must provide proof of such residence as required by the country of jurisdiction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='Country of Residence'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='The birth date of the user.', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(blank=True, default='EUR', help_text='The default currency of the user.', max_length=3, null=True, verbose_name='Default Currency'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='The first names of the user.', max_length=225, null=True, verbose_name='First Names'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='The job title of the user.', max_length=150, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_complete',
            field=models.BooleanField(default=False, help_text='Flag to determine if user has completed KYC verification.', verbose_name='KYC Complete'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_complete_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user completed KYC verification process.', null=True, verbose_name='KYC Complete Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('action_required', 'Action Required'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused')], default='unverified', help_text='The KYC status of the user.', max_length=15, null=True, verbose_name='KYC Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted',
            field=models.BooleanField(default=False, help_text='Flag to determine if user has submitted KYC verification.', verbose_name='KYC Submitted'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last name of the user.', max_length=225, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete',
            field=models.BooleanField(default=False, help_text='Flag to determine if the user has completed onboarding process.', verbose_name='Completed Onboarding'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user completed onboarding process.', null=True, verbose_name='Onboarding Complete Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text="The place of birth of the user. This must match the place of birth as indicated in the user's photo identification.", max_length=150, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, help_text='The IP address recorded at the time of registration.', null=True, verbose_name='Registered IP Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_security_number',
            field=models.CharField(blank=True, help_text='The social security number or BSN of the user. This helps to determine the credit score and also validates the identity of the user.', max_length=50, null=True, verbose_name='Social Security Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text="Timestamp when user's profile was verified.", null=True, verbose_name='Verification Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The email address of the user.', max_length=150, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the user.', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Useraddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the address.', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('current', 'Current Address'), ('permanent', 'Permanent Address')], default='current', help_text='The type of address', max_length=9, verbose_name='Address type')),
                ('address_line_1', models.CharField(help_text='Address line 1 of the user.', max_length=50, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, help_text='Address line 2 of the user.', max_length=50, null=True, verbose_name='Address line 2')),
                ('state', models.CharField(help_text='State or region of the address.', max_length=50, verbose_name='State or Region')),
                ('city', models.CharField(help_text='City of the address.', max_length=50, verbose_name='City')),
                ('zip_post_code', models.CharField(help_text='Zip or postal code of the address.', max_length=20, verbose_name='Zip Code')),
                ('country', models.ForeignKey(help_text='Country of the address.', on_delete=django.db.models.deletion.PROTECT, to='locations.country', verbose_name='Country')),
                ('user', models.ForeignKey(help_text='The user to whom the address belongs.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'User address',
                'verbose_name_plural': 'User addresses',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='current_address',
            field=models.ForeignKey(blank=True, help_text='The current living address of the user.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_address', to='users.useraddress', verbose_name='Current Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address',
            field=models.ForeignKey(blank=True, help_text='The permanent address of the user.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permanent_address', to='users.useraddress', verbose_name='Permanent Address'),
        ),
    ]
