# Generated by Django 4.2.11 on 2024-07-24 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Register User', 'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, help_text='The contact number of the customer.', max_length=50, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='country_of_residence',
            field=models.CharField(blank=True, help_text='The country of residence of the customer. KYC verification will be applied to this country and customer must provide proof of such residence as relevant in the ocuntry of jurisdiction.', max_length=150, null=True, verbose_name='Country of Residence'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_adress',
            field=models.CharField(blank=True, help_text='The current living adress of the customer.', max_length=225, null=True, verbose_name='Current Adress'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, help_text='The birth date of  customer.', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(blank=True, default='EUR', help_text='The default currency of the borrower. Currency will be sent against country of residence.', max_length=3, null=True, verbose_name='Default Currency'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='The first names of the customer.', max_length=225, null=True, verbose_name='First names'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='The job title of the customer.', max_length=150, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_complete',
            field=models.BooleanField(default=False, help_text='Flag to determine if customer has completed KYC verification', verbose_name='KYC Complete'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_complete_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer completed KYC verification process', null=True, verbose_name='KYC Complete Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('action_required', 'Action Required'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused')], default='Unverified', help_text='The KYC Status of the customer', max_length=15, null=True, verbose_name='KYC Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted',
            field=models.BooleanField(default=False, help_text='Flag to determine if customer has submitted a KYC verification process.', verbose_name='KYC Submitted'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last name of the customer.', max_length=225, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete',
            field=models.BooleanField(default=False, help_text='Flag to determine if the customer has completed onboarding process.', verbose_name='Completed Onboarding'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer completed onboarding process.', null=True, verbose_name='Onboarding  Complete Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_adress',
            field=models.CharField(blank=True, help_text='The permanent adress of the customer.', max_length=225, null=True, verbose_name='Permanent Adress'),
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text='The place of birth of the customer. This must match the place of birth as indicated in the customers photo identification.', max_length=150, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_ip_adress',
            field=models.GenericIPAddressField(blank=True, editable=False, help_text='The IP adress recorder at the time of registration.', null=True, verbose_name='Registered IP Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_security_number',
            field=models.CharField(blank=True, help_text='The social security number of the customer. This helps to determine the credit score and also validates tge identity of the custoomer.', max_length=50, null=True, verbose_name='Social Security Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_date',
            field=models.CharField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when customers profile was verified.', null=True, verbose_name='Verification Date'),
        ),
    ]
