# Generated by Django 4.2.11 on 2024-07-31 11:08

from django.db import migrations
import p2plending.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', p2plending.users.managers.UserManager()),
            ],
        ),
    ]
