# Generated by Django 4.2.11 on 2024-08-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_current_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('current', 'Current Address'), ('permanet', 'Permanent Address')], default='current', help_text='The type of adress', max_length=9, verbose_name='Address type'),
        ),
    ]
