# Generated by Django 4.2.11 on 2024-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraddress_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('borrower', 'Borrower'), ('investor', 'Investor')], default='investor', help_text='The account type of the user.', max_length=8, null=True, verbose_name='Account Type'),
        ),
    ]
