# Generated by Django 4.2.11 on 2024-08-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_account_type_and_more'),
        ('users', '0008_user_account_type'),
    ]

    operations = [
    ]
