# Generated by Django 4.2.11 on 2024-08-15 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0009_merge_20240815_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Register User', 'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, help_text='The contact number of the customer.', max_length=50, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_of_residence',
            field=models.ForeignKey(blank=True, help_text='The country of residence of the customer. KYC verification will be applied to this country and customer must provide proof of such residence as relevant in the ocuntry of jurisdiction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='Country of Residence'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_address',
            field=models.ForeignKey(blank=True, help_text='The current living address of the customer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.useraddress', verbose_name='Current address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, help_text='The birth date of  customer.', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=models.CharField(blank=True, default='EUR', help_text='The default currency of the borrower. Currency will be sent against country of residence.', max_length=3, null=True, verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The email adreess of the customer', max_length=150, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='The first names of the customer.', max_length=225, null=True, verbose_name='First names'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifer of the customer.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='The job title of the customer.', max_length=150, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_complete',
            field=models.BooleanField(default=False, help_text='Flag to determine if customer has completed KYC verification', verbose_name='KYC Complete'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_complete_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer completed KYC verification process', null=True, verbose_name='KYC Complete Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('action_required', 'Action Required'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused')], default='Unverified', help_text='The KYC Status of the customer', max_length=15, null=True, verbose_name='KYC Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_submitted',
            field=models.BooleanField(default=False, help_text='Flag to determine if customer has submitted a KYC verification process.', verbose_name='KYC Submitted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last name of the customer.', max_length=225, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='on_boarding_complete',
            field=models.BooleanField(default=False, help_text='Flag to determine if the customer has completed onboarding process.', verbose_name='Completed Onboarding'),
        ),
        migrations.AlterField(
            model_name='user',
            name='on_boarding_complete_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer completed onboarding process.', null=True, verbose_name='Onboarding  Complete Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permanent_address',
            field=models.ForeignKey(blank=True, help_text='The permanent address of the customer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.useraddress', verbose_name='Permanent address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text='The place of birth of the customer. This must match the place of birth as indicated in the customers photo identification.', max_length=150, null=True, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered_ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, help_text='The IP address recorder at the time of registration.', null=True, verbose_name='Registered IP Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_security_number',
            field=models.CharField(blank=True, help_text='The social security number of the customer. This helps to determine the credit score and also validates tge identity of the custoomer.', max_length=50, null=True, verbose_name='Social Security Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_date',
            field=models.CharField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when customers profile was verified.', null=True, verbose_name='Verification Date'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line_1',
            field=models.CharField(help_text='Adress line 1 of the user', max_length=50, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Adress line 2 of the user', max_length=50, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(help_text='The city of the address of the user', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.ForeignKey(help_text='Adress line 1 of the user', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='locations.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the customer.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(help_text='Adress line 1 of the user', max_length=50, verbose_name='State or Region'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('current', 'Current Address'), ('permanet', 'Permanent Address')], default='current', help_text='The type of adress', max_length=9, verbose_name='Address type'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(help_text='The user for whome address belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zip_post_code',
            field=models.CharField(help_text='The zip or postal code of the address of the user', max_length=20, verbose_name='Zip Code'),
        ),
    ]
