# Generated by Django 4.2.11 on 2024-08-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
