# Generated by Django 4.2.11 on 2024-08-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
    ]
