# Generated by Django 4.2.11 on 2024-08-10 12:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifer of an object.', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.CharField(default=django.utils.timezone.now, help_text='Timestamp when the record was modified.', max_length=20, verbose_name='Modified Date')),
                ('name', models.CharField(help_text='Enter field documentation', max_length=20, verbose_name='name')),
                ('designation', models.CharField(help_text='The position of the team member.', max_length=50, verbose_name='Designation')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL', max_length=50, null=True, verbose_name='LinkedIn')),
                ('email', models.CharField(blank=True, help_text="team member's email", max_length=75, null=True, verbose_name='Email')),
                ('photo', models.ImageField(help_text='photo of the team member.', upload_to='team', verbose_name='Photo')),
            ],
            options={
                'verbose_name': ' Team member',
                'verbose_name_plural': 'Team members',
            },
        ),
    ]
