# Generated by Django 4.2.11 on 2024-08-10 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.', verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='modified_date',
            field=models.CharField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was modified.', verbose_name='Modified Date'),
        ),
    ]
